--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/InvMenuUtils
build-by-default: true
branches:
- master
projects:
  InvMenuUtils:
    path: ""
    model: virion
    type: library
...
